name: Release Workflow

on:
  push:
    branches:
      - revision

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Version from init.lua
        id: get_version
        run: |
          version=$(sed -nE 's/_G\.Version = "v([0-9]+\.[0-9]+\.[0-9]+)"/\1/p' init.lua)
          echo "::set-output name=release_name::v$version"
          echo "::set-output name=tag_name::$version"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.tag_name }}
          release_name: ${{ steps.get_version.outputs.release_name }}
          body: |
            ```lua
            loadstring(game:HttpGet("http://gg.gg/Hydronium"))()
            ```
            # Changes
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Upload Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Loadstring.lua
          asset_name: Loadstring.lua
          asset_content_type: text/plain
